### PR TITLE
chore: use match instead of double if

### PR DESCRIPTION
**Pull request by jackwener**
use `match` instead of double `if`

It will make code more clear.

### CODE REVIEW

**Comment by hai-rise** [comment]
Intuitively, if we cannot find `final_account` in `MvMemory`, we would fetch it from `Storage` before registering the **final** value to the read cache. This change seems to not write to the cache if the value is read from storage. I'm surprised that this passes the tests. That could be an optimization we can look into!

Also, I'm hesitant to move the straightforward cache logic into a rather complicated value evaluation & origin tracking code. So yeah, let's keep this open until I can find the time to look into the skip-cache optimization 🙏.

**Comment by jackwener** [comment]
> this passes the tests. 

I feel like you may have some misunderstandings about my code. In my opinion, this PR does not change the code logic.

In this PR, I just move some code into `match`. You can see https://github.com/risechain/pevm/pull/186/files?diff=split&w=1 , this diff is more clear(ignore space_change)

**Comment by hai-rise** [comment]
There is a semantic change as `final_account` can still be set via `match self.vm.storage.basic(&address) {` in the previous `if final_account.is_none() {` branch, right?

So the previous behaviour is that: find `final_account` from `MvMemory`, if not found then try finding it from `Storage`, then write it to `self.read_set.accounts` if we could find one.

The new behaviour here is that it only writes to `self.read_set.accounts` if `final_account` is found from `MvMemory`, and doesn't write if it has fallen back to `Storage.

**Comment by jackwener** [comment]
> There is a semantic change as final_account can still be set via match self.vm.storage.basic(&address) { in the previous if final_account.is_none() {

Get it, Thank you !

**Comment by hai-rise** [comment]
> Hahaha, I feel the same way

Reading accounts from storage is a hot path so it would be a huge win if we could remove the (potentially unneeded) cache write. I'll have a look 🫡.

**Comment by hai-rise** [comment]
@jackwener So the tests still passed because not registering read accounts would make all written values "new" and be recorded in the multi-version data structure. This would hurt performance a lot as ideally we would only record changed values, which we need the read accounts cache to distinguish.

The related code has also changed quite a lot, so I'd suggest closing this PR now 🙏.

**Pull request closed without merging**
