### PR TITLE
impl has_storage

### LINKED ISSUE #340: Implement `has_storage` for `RpcStorage`
https://github.com/risechain/pevm/blob/fa8952bcbf9b25b88acd2b76bfcd0403fb14ce95/src/storage/rpc.rs#L173-L177

### PR DESCRIPTION
**Pull request by malik672**
closes #340

### CODE REVIEW

**Review by hai-rise — CHANGES_REQUESTED** [review]
Almost there! but something like this may be cleaner 🙏:

```rust
fn has_storage(&self, address: &Address) -> Result<bool, Self::Error> {
    let proof = self.fetch(|| {
        self.provider
            // [get_account] is simpler but it yields deserialization
            // error on an empty account.
            .get_proof(*address, Vec::new())
            .block_id(self.block_id)
    })?;
    Ok(proof.storage_hash != alloy_consensus::EMPTY_ROOT_HASH)
}
```

**Comment by malik672** [comment]
done

**Review by hai-rise — CHANGES_REQUESTED** [review]
Can you remove the unused `FixedBytes`? That should pass lint and CI now 🙏.

```
error: unused import: `FixedBytes`
 --> src/storage/rpc.rs:7:33
  |
7 | use alloy_primitives::{Address, FixedBytes, B256, U256};
  |                                 ^^^^^^^^^^
  |
  = note: `-D unused-imports` implied by `-D warnings`
  = help: to override `-D warnings` add `#[allow(unused_imports)]` 
```

**Comment by malik672** [comment]
done, sorry i've not really had much time maybe starting from tomorrow

**Review by hai-rise — APPROVED** [review]
No worries, really appreciate your contributions, any time!

**Pull request merged**
