### PR TITLE
Remove all #![allow(...)]

### PR DESCRIPTION
**Pull request by MuhtasimTanmoy**
Closes https://github.com/risechain/pevm/issues/410

### CODE REVIEW

**Review by hai-rise — CHANGES_REQUESTED** [review]
Let's provide missing docs and work around the unused imports to pass warnings 🙏.

**Comment by i1i1** [comment]
I think there is no workaround for this `allow(unused_crate_dependencies)`. The issue is related to 2 things:
- Rust compiles integration tests and crate itself as different compile targets (that is why you have to use all the dependencies in tests specifically)
- You can't disable lints specifically for tests

So `#![allow(unused_crate_dependencies)]` in each of the tests is probably the best workaround.

Of course tests can be squashed and that would make only 1 `allow` on the very toplevel.

WDUT?

**Comment by hai-rise** [comment]
These false positives are very noisy so I'd vote to remove `unused_crate_dependencies` if there's no clean workaround. Can replace it with `cargo-machete` in the CI but practically, at the current scale we can manually bump and audit dependencies per every Reth or our own release.

**Comment by i1i1** [comment]
Makes sense! False positives are annoying.

Can we make an issue for `cargo machete` or generally for checking unused dependencies? I think it is really important to keep track of it and keep the repo in shape

**Comment by hai-rise** [comment]
Okay, I've opened #420 and @MuhtasimTanmoy let's remove `unused_crate_dependencies` in this CI.

**Comment by MuhtasimTanmoy** [comment]
Done. 

What this config `#![cfg_attr(test, allow(unused_crate_dependencies))]` in `crates/pevm/src/lib.rs` does?

**Comment by hai-rise** [comment]
> What this config `#![cfg_attr(test, allow(unused_crate_dependencies))]` in `crates/pevm/src/lib.rs` does?

It allows `unused_crate_dependencies` for tests which we can also remove now that we've turned off the lint. 

@MuhtasimTanmoy CI is failing for missing docs. It'd be more appropriate for us to add them so let's keep the `allow` in for now, and just make this PR remove `unused_crate_dependencies`. What do you think 🙏?

**Comment by MuhtasimTanmoy** [comment]
> It allows unused_crate_dependencies for tests which we can also remove now that we've turned off the lint.

Done.

Total 63 missing docs. Can we go for bare minimum doc? I was sort of going through the codebase. You can provide some context to some of them.

**Comment by hai-rise** [comment]
> Can we go for bare minimum doc?

@MuhtasimTanmoy Yes, that should work for now as the missing ones are only in test/bench anyway. There's existing `//` that can be quickly converted to `///` too 🙏.

**Comment by MuhtasimTanmoy** [comment]
Going for this approach then.

**Comment by MuhtasimTanmoy** [comment]
Done.  

But two left.

This lines giving `warning: missing documentation for a function`

```
criterion_group!(benches, benchmark_gigagas);
```

After converting to

```
/// Benchmark
criterion_group!(benches, benchmark_gigagas);
```

Showing

```
/// Benchmark
| ^^^^^^^^^^^^^ rustdoc does not generate documentation for macro invocations
```

May be missing something.

**Comment by MuhtasimTanmoy** [comment]
@hai-rise Cant document macro invocation. Also, it's library provided. Any insight? 

Context:
- [Rust document macro invocations](https://amanjeev.com/blog/rust-document-macro-invocations)
- [Generating documentation in macros](https://stackoverflow.com/questions/33999341/generating-documentation-in-macros)

**Comment by i1i1** [comment]
Hey @MuhtasimTanmoy! Thanks again for working on this :pray: 

I think we can't do much about macro invocation, so lets just `#[allow(missing_docs)]` and merge it for now.

I've tried to fix it and it seems it requires some workaround like follows:
```diff
-criterion_group!(benches, criterion_benchmark); 
-criterion_main!(benches);
+#[allow(missing_docs)]
+mod benches {
+    use super::*;
+    criterion_group!(benches, criterion_benchmark);
+}
+
+criterion_main!(benches::benches);
 ```

Could you do smth like this and just add some comment like `// HACK: we can't document public items inside of the macro`? :pray:

**Comment by MuhtasimTanmoy** [comment]
Ok, I  @i1i1

I got a similar solution on StackOverflow from my [question](https://stackoverflow.com/questions/79175703/clippy-warning-on-documentation-for-macro-invocations) as well.

**Comment by MuhtasimTanmoy** [comment]
Done.

**Review by i1i1 — APPROVED** [review]
LGTM! Thanks @MuhtasimTanmoy :)

**Review by i1i1 — CHANGES_REQUESTED** [review]
This is the last thing, but could you run `cargo fmt --all` :pray: ? Check seem to fail

**Review by i1i1 — APPROVED** [review]
Thanks!

**Pull request merged**
